services:
  app:
    container_name: backend
    image: 'kitkat-backend:latest'
    build:
      context: .
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/smartpotdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pass
    env_file:
      - ./.env
    ports:
      - "8080:8080"

  postgres:
    container_name: db
    image: 'postgres:16-alpine'
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: smartpotdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres:
    driver: local
